openapi: 3.0.1

info:
  title: Mannatime API
  description: 언제만나(mannatime) API Docs
  contact:
    email: apiteam@swagger.io
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://dev.swm-bentley-server.link

tags:
  - name: Room
    description: 방
  - name: Participant
    description: 참가자 - 방에 참여하는 인원들에 대한 정보
  - name: Calendar
    description: 캘린더 - 외부 캘린더 불러오기
  - name: Feedback
    description: 피드백 - 사용자 피드백

paths:
  /room:
    post:
      tags:
        - Room
      summary: 새로운 방 생성
      operationId: createRoom
      requestBody:
        $ref: 'requestBodies/roomRequest.yaml'
      responses:
        400:
          $ref: 'errors/room400Error.yaml'

  /room/{roomUuid}:
    get:
      tags:
        - Room
      summary: 방 정보 불러오기
      operationId: getRoomInfo
      parameters:
        - $ref: 'parameters/roomUuid.yaml'
      responses:
        200:
          $ref: 'responses/roomResponse.yaml'
        404:
          $ref: 'errors/room404Error.yaml'

  /room/{roomUuid}/participant/entry:
    post:
      tags:
        - Participant
      summary: 비회원 방 입장
      operationId: participantFind
      parameters:
        - $ref: 'parameters/roomUuid.yaml'
      requestBody:
        $ref: '/requestBodies/participantEntryRequest.yaml'
      responses:
        200:
          $ref: '/responses/participantEntryResponse.yaml'
        401:
          $ref: '/errors/participant401Error.yaml'
        404:
          $ref: '/errors/room404Error.yaml'

  /room/{roomUuid}/participant/available:
    post:
      tags:
        - Participant
      summary: 비회원 가능한 시간 입력
      operationId: participantAvailablePost
      parameters:
        - $ref: '/parameters/roomUuid.yaml'
      requestBody:
        $ref: '/requestBodies/participantAvailableRequest.yaml'
      responses:
        200:
          description: "200 OK"
          content: {}
        404:
          $ref: '/errors/room404Error.yaml'

  /room/{roomUuid}/group:
    get:
      tags:
        - Participant
      summary: 비회원 방 입장
      operationId: groupSchedulesFind
      parameters:
        - $ref: '/parameters/roomUuid.yaml'
      responses:
        200:
          $ref: '/responses/groupResponse.yaml'
        404:
          $ref: '/errors/room404Error.yaml'

  /room/{roomUuid}/participant/google/{code}:
    get:
      tags:
        - Calendar
      summary: "비회원 구글 캘린더 연동"
      operationId: unSignedUserCalendarFind
      parameters:
        - $ref: '/parameters/roomUuid.yaml'
        - $ref: '/parameters/authorizationCode.yaml'
      responses:
        200:
          $ref: '/responses/googleCalendarResponse.yaml'
        500:
          description: "INTERNAL SERVER ERROR"
          content: {}

  /google/login:
    get:
      tags:
        - Calendar
      summary: "구글 캘린더 테스트용"
      operationId: moveGoogleInitUrl
      responses:
        200:
          $ref: '/responses/googleCalendarResponse.yaml'

  /feedback:
    $ref: '/paths/postFeedback.yaml'